// AUTO-GENERATED by ebely (generateClient) — НЕ редактировать вручную.
// Источник: Test Backend (oRPC) v1.0.0
// Режим клиента: test
// Перегенерация: pnpm run client:generate

import { BaseStore, ApiResponse, HookRegistry } from "ebely"
import type { BeforeHook, AfterHook } from "ebely"
import { ebely } from "./ebely"

type RequestInput = {
  path?: Record<string, string>
  query?: Record<string, string | number | boolean | undefined>
  body?: unknown
}

type RequestFn = (req: {
  method: string
  path: string
  opKey: string
  input?: RequestInput
}) => Promise<{ status: number; body: unknown }>

export type CreateUserArgs = {
  /** Заголовки, которые будут добавляться ко всем запросам этого пользователя. */
  headers?: Record<string, string>
}

export type WorldApi = {
    "posts": {
      "list": (input?: {}) => Promise<ApiResponse<{ 200: Array<{
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        }> }>>
      "create": (input: { body: {
          "title": string
          "content": string
        } }) => Promise<ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>>
      "get": (input: { path: { "id": string } }) => Promise<ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>>
      "update": (input: { path: { "id": string }; body?: {
          "title"?: string
          "content"?: string
        } }) => Promise<ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>>
      "delete": (input: { path: { "id": string } }) => Promise<ApiResponse<{ 200: {
          "success": boolean
        } }>>
    }
    "auth": {
      "register": (input: { body: {
          "email": string
          "password": string
        } }) => Promise<ApiResponse<{ 200: {
          "email": string
          "password": string
        } }>>
      "confirm": (input: { body: {
          "code": string
        } }) => Promise<ApiResponse<{ 200: {
          "code": string
        } }>>
      "getGetSession": (input?: {}) => Promise<ApiResponse<{ 200: {
          "user": string
          "method": string
        } }>>
      "postGetSession": (input: { body: {
          "token": string
        } }) => Promise<ApiResponse<{ 200: {
          "user": string
          "method": string
        } }>>
    }
    "admin": {
      "clearDatabase": (input?: {}) => Promise<ApiResponse<{ 200: {
          "success": boolean
        } }>>
    }
}

type EbelyHookTree<Store extends BaseStore> = {
    globalBefore(fn: BeforeHook<Store>): void
    globalAfter(fn: AfterHook<Store>): void
    "posts": {
      "list": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, Array<{
        "id": string
        "title": string
        "content": string
        "createdAt": string
        "updatedAt": string
      }>>): void
      }
      "create": {
        before(fn: BeforeHook<Store, {
          "title": string
          "content": string
        }>): void
        after(fn: AfterHook<Store, {
          "title": string
          "content": string
        }, {
        "id": string
        "title": string
        "content": string
        "createdAt": string
        "updatedAt": string
      }>): void
      }
      "get": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, {
        "id": string
        "title": string
        "content": string
        "createdAt": string
        "updatedAt": string
      }>): void
      }
      "update": {
        before(fn: BeforeHook<Store, {
          "title"?: string
          "content"?: string
        }>): void
        after(fn: AfterHook<Store, {
          "title"?: string
          "content"?: string
        }, {
        "id": string
        "title": string
        "content": string
        "createdAt": string
        "updatedAt": string
      }>): void
      }
      "delete": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, {
        "success": boolean
      }>): void
      }
    }
    "auth": {
      "register": {
        before(fn: BeforeHook<Store, {
          "email": string
          "password": string
        }>): void
        after(fn: AfterHook<Store, {
          "email": string
          "password": string
        }, {
        "email": string
        "password": string
      }>): void
      }
      "confirm": {
        before(fn: BeforeHook<Store, {
          "code": string
        }>): void
        after(fn: AfterHook<Store, {
          "code": string
        }, {
        "code": string
      }>): void
      }
      "getGetSession": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, {
        "user": string
        "method": string
      }>): void
      }
      "postGetSession": {
        before(fn: BeforeHook<Store, {
          "token": string
        }>): void
        after(fn: AfterHook<Store, {
          "token": string
        }, {
        "user": string
        "method": string
      }>): void
      }
    }
    "admin": {
      "clearDatabase": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, {
        "success": boolean
      }>): void
      }
    }
}

/**
 * Тип регистратора хуков для ЭТОГО бэкенда. Объявите хуки в отдельном
 * файле и положите одной переменной в конфиг (`EbelyConfig.hooks`).
 * Передайте СВОЙ класс store параметром, чтобы `ctx` был типизирован:
 *
 *   import type { UserStore } from './userStore'
 *   export const hooks: Hooks<UserStore> = (h) => {
 *     h.posts.create.after(({ response, ctx }) => { … })
 *   }
 *
 * (Параметр НЕ выводится из `ebely.userStore` намеренно: это создало
 * бы цикл типов `ebely` ⇄ `Hooks`, т.к. `hooks` лежит внутри `ebely`.)
 */
export type Hooks<Store extends BaseStore = BaseStore> = (
  h: EbelyHookTree<Store>,
) => void

/**
 * База `World` — это сконфигурированный `ebely.worldStore` (или пустой
 * `BaseStore`, если не задан). Поэтому `world.<сценарий>()` и
 * `world.get/set` доступны и типизированы ровно как у пользователя,
 * только область — весь мир. Тип берётся из `ebely` тем же приёмом, что
 * и `Store` (никаких рантайм-условий — см. ARCHITECTURE.md §8).
 */
type ConfiguredWorldStore =
  typeof ebely extends { worldStore: new () => infer I extends BaseStore }
    ? I
    : BaseStore
const WorldStoreBase = ((ebely as { worldStore?: new () => BaseStore })
  .worldStore ?? BaseStore) as new () => ConfiguredWorldStore

export class World<
  Store extends BaseStore = InstanceType<typeof ebely.userStore>,
> extends WorldStoreBase {
  /**
   * Общий реестр хуков. Регистрация — статическая (один раз из конфига),
   * но `ctx` подставляется в момент запроса = store конкретного юзера.
   */
  private hookRegistry = new HookRegistry()

  constructor(
    public args: {
      /** URL бэкенда. Если не задан — берётся ebely.url из конфига. */
      url?: string
      /** Класс-хранилище. Если не задан — берётся ebely.userStore. */
      store?: new () => Store
    } = {},
  ) {
    super()
    const registrar = (ebely as { hooks?: (h: unknown) => void }).hooks
    if (registrar) registrar(this.buildHookTree())
    // world-store ходит АНОНИМНЫМ клиентом (без per-user заголовков);
    // ctx хуков для таких вызовов = сам world.
    ;(this as unknown as { api: unknown }).api = this.buildApiTree(
      this.makeRequest({ headers: {}, store: this }),
    )
  }

  /** Базовый URL с учётом server.url из схемы. */
  private baseUrl(): string {
    return (this.args.url ?? ebely.url).replace(/\/$/, '') + "/api"
  }

  private buildHookTree(): EbelyHookTree<Store> {
    const r = this.hookRegistry
    return {
      globalBefore: (fn: BeforeHook<Store>) => r.globalBefore({ fn }),
      globalAfter: (fn: AfterHook<Store>) => r.globalAfter({ fn }),
      "posts": {
        "list": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.list", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.list", fn }),
        },
        "create": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.create", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.create", fn }),
        },
        "get": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.get", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.get", fn }),
        },
        "update": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.update", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.update", fn }),
        },
        "delete": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.delete", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.delete", fn }),
        },
      },
      "auth": {
        "register": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "auth.register", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "auth.register", fn }),
        },
        "confirm": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "auth.confirm", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "auth.confirm", fn }),
        },
        "getGetSession": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "auth.getGetSession", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "auth.getGetSession", fn }),
        },
        "postGetSession": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "auth.postGetSession", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "auth.postGetSession", fn }),
        },
      },
      "admin": {
        "clearDatabase": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "admin.clearDatabase", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "admin.clearDatabase", fn }),
        },
      },
    } as unknown as EbelyHookTree<Store>
  }

  /**
   * Создаёт `request`, замкнутый на заголовки и `store` (он же `ctx`
   * хуков). Один и тот же движок и для пользователя, и для world.
   */
  private makeRequest(cfg: {
    headers: Record<string, string>
    store: BaseStore
  }): RequestFn {
    const baseUrl = this.baseUrl()
    const registry = this.hookRegistry
    const { headers: baseHeaders, store } = cfg

    return async (req): Promise<{ status: number; body: unknown }> => {
      const { method, path, opKey, input } = req

      const hookReq = {
        method,
        path,
        pathParams: { ...(input?.path ?? {}) },
        query: { ...(input?.query ?? {}) },
        body: input?.body,
        headers: { ...baseHeaders },
      }
      await registry.runBefore({ key: opKey, request: hookReq, ctx: store })

      let resolvedPath = path
      for (const [k, v] of Object.entries(hookReq.pathParams)) {
        resolvedPath = resolvedPath.replace(
          `{${k}}`,
          encodeURIComponent(String(v)),
        )
      }

      const url = new URL(baseUrl + resolvedPath)
      for (const [k, v] of Object.entries(hookReq.query)) {
        if (v !== undefined) url.searchParams.set(k, String(v))
      }

      const hasBody = hookReq.body !== undefined
      const response = await fetch(url, {
        method,
        headers: {
          ...(hasBody ? { 'content-type': 'application/json' } : {}),
          ...hookReq.headers,
        },
        body: hasBody ? JSON.stringify(hookReq.body) : undefined,
      })

      const text = await response.text()
      let data: unknown
      try {
        data = text ? JSON.parse(text) : undefined
      } catch {
        data = text
      }

      await registry.runAfter({
        key: opKey,
        request: hookReq,
        response: { status: response.status, body: data },
        ctx: store,
      })

      return { status: response.status, body: data }
    }
  }

  /** Дерево типизированных вызовов эндпоинтов поверх одного `request`. */
  private buildApiTree(request: RequestFn) {
    return {
      "posts": {

        /** List all posts */
        "list": async (input?: {}): Promise<ApiResponse<{ 200: Array<{
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        }> }>> => {
          const res = await request({
            method: "GET",
            path: "/posts",
            opKey: "posts.list",
            input: input as RequestInput,
          })
          return new ApiResponse(res) as unknown as ApiResponse<{ 200: Array<{
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        }> }>
        },

        /** Create a post */
        "create": async (input: { body: {
          "title": string
          "content": string
        } }): Promise<ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>> => {
          const res = await request({
            method: "POST",
            path: "/posts",
            opKey: "posts.create",
            input: input as RequestInput,
          })
          return new ApiResponse(res) as unknown as ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>
        },

        /** Get a single post by id */
        "get": async (input: { path: { "id": string } }): Promise<ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>> => {
          const res = await request({
            method: "GET",
            path: "/posts/{id}",
            opKey: "posts.get",
            input: input as RequestInput,
          })
          return new ApiResponse(res) as unknown as ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>
        },

        /** Update a post */
        "update": async (input: { path: { "id": string }; body?: {
          "title"?: string
          "content"?: string
        } }): Promise<ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>> => {
          const res = await request({
            method: "PATCH",
            path: "/posts/{id}",
            opKey: "posts.update",
            input: input as RequestInput,
          })
          return new ApiResponse(res) as unknown as ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>
        },

        /** Delete a post */
        "delete": async (input: { path: { "id": string } }): Promise<ApiResponse<{ 200: {
          "success": boolean
        } }>> => {
          const res = await request({
            method: "DELETE",
            path: "/posts/{id}",
            opKey: "posts.delete",
            input: input as RequestInput,
          })
          return new ApiResponse(res) as unknown as ApiResponse<{ 200: {
          "success": boolean
        } }>
        },
      },
      "auth": {

        /** Register (stub: echoes input) */
        "register": async (input: { body: {
          "email": string
          "password": string
        } }): Promise<ApiResponse<{ 200: {
          "email": string
          "password": string
        } }>> => {
          const res = await request({
            method: "POST",
            path: "/auth/register",
            opKey: "auth.register",
            input: input as RequestInput,
          })
          return new ApiResponse(res) as unknown as ApiResponse<{ 200: {
          "email": string
          "password": string
        } }>
        },

        /** Confirm registration code (stub: echoes input) */
        "confirm": async (input: { body: {
          "code": string
        } }): Promise<ApiResponse<{ 200: {
          "code": string
        } }>> => {
          const res = await request({
            method: "POST",
            path: "/auth/confirm",
            opKey: "auth.confirm",
            input: input as RequestInput,
          })
          return new ApiResponse(res) as unknown as ApiResponse<{ 200: {
          "code": string
        } }>
        },

        /** Read current session (stub) */
        "getGetSession": async (input?: {}): Promise<ApiResponse<{ 200: {
          "user": string
          "method": string
        } }>> => {
          const res = await request({
            method: "GET",
            path: "/auth/session",
            opKey: "auth.getGetSession",
            input: input as RequestInput,
          })
          return new ApiResponse(res) as unknown as ApiResponse<{ 200: {
          "user": string
          "method": string
        } }>
        },

        /** Refresh current session (stub) */
        "postGetSession": async (input: { body: {
          "token": string
        } }): Promise<ApiResponse<{ 200: {
          "user": string
          "method": string
        } }>> => {
          const res = await request({
            method: "POST",
            path: "/auth/session",
            opKey: "auth.postGetSession",
            input: input as RequestInput,
          })
          return new ApiResponse(res) as unknown as ApiResponse<{ 200: {
          "user": string
          "method": string
        } }>
        },
      },
      "admin": {

        /** Wipe all in-memory data */
        "clearDatabase": async (input?: {}): Promise<ApiResponse<{ 200: {
          "success": boolean
        } }>> => {
          const res = await request({
            method: "POST",
            path: "/admin/clear-database",
            opKey: "admin.clearDatabase",
            input: input as RequestInput,
          })
          return new ApiResponse(res) as unknown as ApiResponse<{ 200: {
          "success": boolean
        } }>
        },
      },
    }
  }

  /**
   * Создаёт «пользователя» — изолированный набор типизированных вызовов
   * эндпоинтов, который под капотом ходит fetch-запросами. `store.api`
   * указывает на то же дерево, поэтому методы-сценарии этого store
   * (`fullRegister` и т.п.) ходят от лица именно этого пользователя.
   */
  createUser(userArgs: CreateUserArgs = {}) {
    const StoreClass =
      this.args.store ?? (ebely.userStore as unknown as new () => Store)
    const store = new StoreClass()
    const tree = this.buildApiTree(
      this.makeRequest({ headers: { ...userArgs.headers }, store }),
    )
    ;(store as unknown as { api: unknown }).api = tree
    return Object.assign(store, tree)
  }
}
