// AUTO-GENERATED by ebely (generateClient) — НЕ редактировать вручную.
// Источник: Test Backend (oRPC) v1.0.0
// Режим клиента: test
// Перегенерация: pnpm run client:generate

import { InternalStore, ApiResponse } from "ebely"
import { ebely } from "./ebely"

type RequestInput = {
  path?: Record<string, string>
  query?: Record<string, string | number | boolean | undefined>
  body?: unknown
}

export type CreateUserArgs = {
  /** Заголовки, которые будут добавляться ко всем запросам этого пользователя. */
  headers?: Record<string, string>
}

export class World<
  Store extends InternalStore = InstanceType<typeof ebely.internalStore>,
> {
  constructor(
    public args: {
      /** URL бэкенда. Если не задан — берётся ebely.url из конфига. */
      url?: string
      /** Класс-хранилище. Если не задан — берётся ebely.internalStore. */
      store?: new () => Store
    } = {},
  ) {}

  /** Базовый URL с учётом server.url из схемы. */
  private baseUrl(): string {
    return (this.args.url ?? ebely.url).replace(/\/$/, '') + "/api"
  }

  /**
   * Создаёт «пользователя» — изолированный набор типизированных вызовов
   * эндпоинтов, который под капотом ходит fetch-запросами.
   */
  createUser(userArgs: CreateUserArgs = {}) {
    const baseUrl = this.baseUrl()
    const StoreClass =
      this.args.store ?? (ebely.internalStore as unknown as new () => Store)
    const store = new StoreClass()

    const request = async (req: {
      method: string
      path: string
      input?: RequestInput
    }): Promise<{ status: number; body: unknown }> => {
      const { method, path, input } = req

      let resolvedPath = path
      for (const [key, value] of Object.entries(input?.path ?? {})) {
        resolvedPath = resolvedPath.replace(
          `{${key}}`,
          encodeURIComponent(String(value)),
        )
      }

      const url = new URL(baseUrl + resolvedPath)
      for (const [key, value] of Object.entries(input?.query ?? {})) {
        if (value !== undefined) url.searchParams.set(key, String(value))
      }

      const hasBody = input?.body !== undefined
      const response = await fetch(url, {
        method,
        headers: {
          ...(hasBody ? { 'content-type': 'application/json' } : {}),
          ...userArgs.headers,
        },
        body: hasBody ? JSON.stringify(input!.body) : undefined,
      })

      const text = await response.text()
      let data: unknown
      try {
        data = text ? JSON.parse(text) : undefined
      } catch {
        data = text
      }

      return { status: response.status, body: data }
    }

    return Object.assign(store, {
      "posts": {

        /** List all posts */
        "list": async (input?: {}): Promise<ApiResponse<{ 200: Array<{
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        }> }>> => {
          const res = await request({
            method: "GET",
            path: "/posts",
            input: input as RequestInput,
          })
          return new ApiResponse(res) as unknown as ApiResponse<{ 200: Array<{
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        }> }>
        },

        /** Create a post */
        "create": async (input: { body: {
          "title": string
          "content": string
        } }): Promise<ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>> => {
          const res = await request({
            method: "POST",
            path: "/posts",
            input: input as RequestInput,
          })
          return new ApiResponse(res) as unknown as ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>
        },

        /** Get a single post by id */
        "get": async (input: { path: { "id": string } }): Promise<ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>> => {
          const res = await request({
            method: "GET",
            path: "/posts/{id}",
            input: input as RequestInput,
          })
          return new ApiResponse(res) as unknown as ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>
        },

        /** Update a post */
        "update": async (input: { path: { "id": string }; body?: {
          "title"?: string
          "content"?: string
        } }): Promise<ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>> => {
          const res = await request({
            method: "PATCH",
            path: "/posts/{id}",
            input: input as RequestInput,
          })
          return new ApiResponse(res) as unknown as ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>
        },

        /** Delete a post */
        "delete": async (input: { path: { "id": string } }): Promise<ApiResponse<{ 200: {
          "success": boolean
        } }>> => {
          const res = await request({
            method: "DELETE",
            path: "/posts/{id}",
            input: input as RequestInput,
          })
          return new ApiResponse(res) as unknown as ApiResponse<{ 200: {
          "success": boolean
        } }>
        },
      },
    })
  }
}
