// AUTO-GENERATED by ebely (generateClient) — НЕ редактировать вручную.
// Источник: Test Backend (oRPC) v1.0.0
// Режим клиента: test
// Перегенерация: pnpm run client:generate

import { InternalStore, ApiResponse, HookRegistry } from "ebely"
import type { BeforeHook, AfterHook } from "ebely"
import { ebely } from "./ebely"

type RequestInput = {
  path?: Record<string, string>
  query?: Record<string, string | number | boolean | undefined>
  body?: unknown
}

export type CreateUserArgs = {
  /** Заголовки, которые будут добавляться ко всем запросам этого пользователя. */
  headers?: Record<string, string>
}

type EbelyHookTree<Store extends InternalStore> = {
    "posts": {
      "list": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, Array<{
        "id": string
        "title": string
        "content": string
        "createdAt": string
        "updatedAt": string
      }>>): void
      }
      "create": {
        before(fn: BeforeHook<Store, {
          "title": string
          "content": string
        }>): void
        after(fn: AfterHook<Store, {
          "title": string
          "content": string
        }, {
        "id": string
        "title": string
        "content": string
        "createdAt": string
        "updatedAt": string
      }>): void
      }
      "get": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, {
        "id": string
        "title": string
        "content": string
        "createdAt": string
        "updatedAt": string
      }>): void
      }
      "update": {
        before(fn: BeforeHook<Store, {
          "title"?: string
          "content"?: string
        }>): void
        after(fn: AfterHook<Store, {
          "title"?: string
          "content"?: string
        }, {
        "id": string
        "title": string
        "content": string
        "createdAt": string
        "updatedAt": string
      }>): void
      }
      "delete": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, {
        "success": boolean
      }>): void
      }
    }
}

/**
 * Тип регистратора хуков для ЭТОГО бэкенда. Объявите хуки в отдельном
 * файле и положите одной переменной в конфиг (`EbelyConfig.hooks`).
 * Передайте СВОЙ класс store параметром, чтобы `ctx` был типизирован:
 *
 *   import type { AppStore } from './internalVariable'
 *   export const hooks: Hooks<AppStore> = (h) => {
 *     h.posts.create.after(({ response, ctx }) => { … })
 *   }
 *
 * (Параметр НЕ выводится из `ebely.internalStore` намеренно: это создало
 * бы цикл типов `ebely` ⇄ `Hooks`, т.к. `hooks` лежит внутри `ebely`.)
 */
export type Hooks<Store extends InternalStore = InternalStore> = (
  h: EbelyHookTree<Store>,
) => void

export class World<
  Store extends InternalStore = InstanceType<typeof ebely.internalStore>,
> {
  /**
   * Общий реестр хуков. Регистрация — статическая (один раз из конфига),
   * но `ctx` подставляется в момент запроса = store конкретного юзера.
   */
  private hookRegistry = new HookRegistry()

  constructor(
    public args: {
      /** URL бэкенда. Если не задан — берётся ebely.url из конфига. */
      url?: string
      /** Класс-хранилище. Если не задан — берётся ebely.internalStore. */
      store?: new () => Store
    } = {},
  ) {
    const registrar = (ebely as { hooks?: (h: unknown) => void }).hooks
    if (registrar) registrar(this.buildHookTree())
  }

  /** Базовый URL с учётом server.url из схемы. */
  private baseUrl(): string {
    return (this.args.url ?? ebely.url).replace(/\/$/, '') + "/api"
  }

  private buildHookTree(): EbelyHookTree<Store> {
    const r = this.hookRegistry
    return {
      "posts": {
        "list": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.list", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.list", fn }),
        },
        "create": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.create", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.create", fn }),
        },
        "get": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.get", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.get", fn }),
        },
        "update": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.update", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.update", fn }),
        },
        "delete": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.delete", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.delete", fn }),
        },
      },
    } as unknown as EbelyHookTree<Store>
  }

  /**
   * Создаёт «пользователя» — изолированный набор типизированных вызовов
   * эндпоинтов, который под капотом ходит fetch-запросами.
   */
  createUser(userArgs: CreateUserArgs = {}) {
    const baseUrl = this.baseUrl()
    const registry = this.hookRegistry
    const StoreClass =
      this.args.store ?? (ebely.internalStore as unknown as new () => Store)
    const store = new StoreClass()

    const request = async (req: {
      method: string
      path: string
      opKey: string
      input?: RequestInput
    }): Promise<{ status: number; body: unknown }> => {
      const { method, path, opKey, input } = req

      const hookReq = {
        method,
        path,
        pathParams: { ...(input?.path ?? {}) },
        query: { ...(input?.query ?? {}) },
        body: input?.body,
        headers: { ...userArgs.headers },
      }
      await registry.runBefore({ key: opKey, request: hookReq, ctx: store })

      let resolvedPath = path
      for (const [k, v] of Object.entries(hookReq.pathParams)) {
        resolvedPath = resolvedPath.replace(
          `{${k}}`,
          encodeURIComponent(String(v)),
        )
      }

      const url = new URL(baseUrl + resolvedPath)
      for (const [k, v] of Object.entries(hookReq.query)) {
        if (v !== undefined) url.searchParams.set(k, String(v))
      }

      const hasBody = hookReq.body !== undefined
      const response = await fetch(url, {
        method,
        headers: {
          ...(hasBody ? { 'content-type': 'application/json' } : {}),
          ...hookReq.headers,
        },
        body: hasBody ? JSON.stringify(hookReq.body) : undefined,
      })

      const text = await response.text()
      let data: unknown
      try {
        data = text ? JSON.parse(text) : undefined
      } catch {
        data = text
      }

      await registry.runAfter({
        key: opKey,
        request: hookReq,
        response: { status: response.status, body: data },
        ctx: store,
      })

      return { status: response.status, body: data }
    }

    return Object.assign(store, {
      "posts": {

        /** List all posts */
        "list": async (input?: {}): Promise<ApiResponse<{ 200: Array<{
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        }> }>> => {
          const res = await request({
            method: "GET",
            path: "/posts",
            opKey: "posts.list",
            input: input as RequestInput,
          })
          return new ApiResponse(res) as unknown as ApiResponse<{ 200: Array<{
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        }> }>
        },

        /** Create a post */
        "create": async (input: { body: {
          "title": string
          "content": string
        } }): Promise<ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>> => {
          const res = await request({
            method: "POST",
            path: "/posts",
            opKey: "posts.create",
            input: input as RequestInput,
          })
          return new ApiResponse(res) as unknown as ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>
        },

        /** Get a single post by id */
        "get": async (input: { path: { "id": string } }): Promise<ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>> => {
          const res = await request({
            method: "GET",
            path: "/posts/{id}",
            opKey: "posts.get",
            input: input as RequestInput,
          })
          return new ApiResponse(res) as unknown as ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>
        },

        /** Update a post */
        "update": async (input: { path: { "id": string }; body?: {
          "title"?: string
          "content"?: string
        } }): Promise<ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>> => {
          const res = await request({
            method: "PATCH",
            path: "/posts/{id}",
            opKey: "posts.update",
            input: input as RequestInput,
          })
          return new ApiResponse(res) as unknown as ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>
        },

        /** Delete a post */
        "delete": async (input: { path: { "id": string } }): Promise<ApiResponse<{ 200: {
          "success": boolean
        } }>> => {
          const res = await request({
            method: "DELETE",
            path: "/posts/{id}",
            opKey: "posts.delete",
            input: input as RequestInput,
          })
          return new ApiResponse(res) as unknown as ApiResponse<{ 200: {
          "success": boolean
        } }>
        },
      },
    })
  }
}
