// AUTO-GENERATED by eberly (generateClient) — НЕ редактировать вручную.
// Источник: Nest example API v1.0.0
// Режим клиента: test
// Перегенерация: pnpm run client:generate

import { BaseStore, ApiResponse, HookRegistry, assertHostAllowed, toMultipartFormData } from "eberly"
import type { BeforeHook, AfterHook, RetryHook } from "eberly"
import type { FileInput, FileEncoding, FileFieldMeta } from "eberly"
import { eberly } from "./eberly"

export type RegisterDto = {
  /** Unique email. Used as the login. */
  "email": string
  /** Password, at least 6 characters. */
  "password": string
}

export type UserDto = {
  /** User id. */
  "id": number
  /** Email the user registered with. */
  "email": string
  /** Avatar URL. `null` until the user uploads an avatar. */
  "avatarUrl": string | null
}

export type ErrorDto = {
  /** HTTP status code. */
  "statusCode": number
  /** Error message. Validation errors (400) return a list: one message per failed constraint. */
  "message": string | Array<string>
  /** HTTP status text, e.g. "Not Found". */
  "error"?: string
}

export type LoginDto = {
  /** Email the user registered with. */
  "email": string
  /** User password. */
  "password": string
}

export type TokenDto = {
  /** Send it as `Authorization: Bearer <accessToken>`. */
  "accessToken": string
  /** The logged-in user. */
  "user": UserDto
}

export type PostDto = {
  /** Post id. */
  "id": number
  /** Post title. */
  "title": string
  /** Post body. */
  "content": string
  /** Id of the user who created the post. */
  "authorId": number
  /** When the post was published. `null` while the post is a draft. */
  "publishedAt": string | null
  /** When the post was created. */
  "createdAt": string
}

export type CreatePostDto = {
  /** Post title, non-empty. */
  "title": string
  /** Post body, non-empty. */
  "content": string
}

export type CreateCommentDto = {
  /** Comment text, non-empty. */
  "text": string
  /** Id of the comment to reply to. It must belong to the same post. Omit for a top-level comment. */
  "parentId"?: number
}

export type CommentDto = {
  /** Comment id. */
  "id": number
  /** Comment text. */
  "text": string
  /** Id of the user who wrote the comment. */
  "authorId": number
  /** Replies to this comment, oldest first. */
  "replies": Array<CommentDto>
}

const FILE_OPS: Record<string, FileFieldMeta[]> = {
  "users.uploadAvatar": [{ name: "file", array: false }],
}

type RequestInput = {
  path?: Record<string, string>
  query?: Record<string, string | number | boolean | undefined>
  body?: unknown
}

type RequestFn = (req: {
  method: string
  path: string
  opKey: string
  input?: RequestInput
}) => Promise<{ status: number; body: unknown }>

export type CreateUserArgs = {
  /** Заголовки, которые будут добавляться ко всем запросам этого пользователя. */
  headers?: Record<string, string>
}

export type WorldApi = {
    "auth": {
      /**
       * Register a new user
       *
       * Creates a user. Email must be unique. Does not log in: call `POST /auth/login` to get a token.
       *
       * `POST /auth/register`
       */
      "register": (input: { body: RegisterDto }) => Promise<ApiResponse<{ 201: UserDto; 400: ErrorDto; 409: ErrorDto }>>
      /**
       * Log in
       *
       * Exchanges email and password for an access token and returns the user. Every login issues a new token; old tokens stay valid.
       *
       * `POST /auth/login`
       */
      "login": (input: { body: LoginDto }) => Promise<ApiResponse<{ 200: TokenDto; 401: ErrorDto }>>
      /**
       * Current user
       *
       * Returns the user the bearer token belongs to.
       *
       * `GET /auth/me`
       */
      "me": (input?: {}) => Promise<ApiResponse<{ 200: UserDto; 401: ErrorDto }>>
      /**
       * Current user (deprecated)
       *
       * Same as `GET /auth/me`. Kept for old clients, use `GET /auth/me` instead.
       *
       * `GET /auth/whoami`
       * @deprecated
       */
      "whoami": (input?: {}) => Promise<ApiResponse<{ 200: UserDto; 401: ErrorDto }>>
    }
    "posts": {
      /**
       * List published posts
       *
       * Returns published posts in creation order. Drafts (`publishedAt: null`) are never listed, even to their author.
       *
       * `GET /posts`
       */
      "list": (input?: { query?: {
          /** Only return posts of this author. */
          "authorId"?: string | number | boolean
        } }) => Promise<ApiResponse<{ 200: Array<PostDto> }>>
      /**
       * Create a post
       *
       * Creates a draft (`publishedAt: null`) owned by the current user. Publish it with `POST /posts/{id}/publish`.
       *
       * `POST /posts`
       */
      "create": (input: { body: CreatePostDto }) => Promise<ApiResponse<{ 201: PostDto; 400: ErrorDto; 401: ErrorDto }>>
      /**
       * Get a post by id
       *
       * Returns any post, drafts included. No authorization needed.
       *
       * `GET /posts/{id}`
       */
      "get": (input: { path: {
          /** Post id. */
          "id": string
        } }) => Promise<ApiResponse<{ 200: PostDto; 404: ErrorDto }>>
      /**
       * Delete a post
       *
       * Deletes the post and all its comments. Only the author may delete, otherwise 403.
       *
       * `DELETE /posts/{id}`
       */
      "remove": (input: { path: {
          /** Post id. */
          "id": string
        } }) => Promise<ApiResponse<{ 204: unknown; 401: ErrorDto; 403: ErrorDto; 404: ErrorDto }>>
      /**
       * Publish a post
       *
       * Sets `publishedAt` to the current time. Only the author may publish, otherwise 403. Publishing an already published post keeps the original `publishedAt`.
       *
       * `POST /posts/{id}/publish`
       */
      "publish": (input: { path: {
          /** Post id. */
          "id": string
        } }) => Promise<ApiResponse<{ 200: PostDto; 401: ErrorDto; 403: ErrorDto; 404: ErrorDto }>>
    }
    "comments": {
      /**
       * Comment tree of a post
       *
       * Returns top-level comments, oldest first. Replies are nested in `replies` at any depth.
       *
       * `GET /posts/{id}/comments`
       */
      "list": (input: { path: {
          /** Post id. */
          "id": string
        } }) => Promise<ApiResponse<{ 200: Array<CommentDto>; 404: ErrorDto }>>
      /**
       * Comment on a post
       *
       * Adds a comment to any post, drafts included. Pass `parentId` to reply to another comment of the same post.
       *
       * `POST /posts/{id}/comments`
       */
      "create": (input: { path: {
          /** Post id. */
          "id": string
        }; body: CreateCommentDto }) => Promise<ApiResponse<{ 201: CommentDto; 400: ErrorDto; 401: ErrorDto; 404: ErrorDto }>>
    }
    "users": {
      /**
       * Upload an avatar
       *
       * Sets the avatar of the current user. Any file is accepted; `avatarUrl` becomes `/avatars/<userId><ext>`, where the extension comes from the uploaded file name. Uploading again replaces the avatar.
       *
       * `POST /users/me/avatar`
       */
      "uploadAvatar": (input: { body: {
          /** The image file. */
          "file": FileInput
        } }) => Promise<ApiResponse<{ 201: UserDto; 400: ErrorDto; 401: ErrorDto }>>
    }
    "test": {
      /**
       * Reset all data
       *
       * Deletes all users, tokens, posts and comments, and restarts ids from 1. Exists only when the server runs with `TEST_MODE=1`.
       *
       * `POST /test/reset`
       */
      "reset": (input?: {}) => Promise<ApiResponse<{ 200: {
          "ok": boolean
        } }>>
    }
}

type EberlyHookTree<Store extends BaseStore> = {
    globalBefore(fn: BeforeHook<Store>): void
    globalAfter(fn: AfterHook<Store>): void
    globalRetry(fn: RetryHook<Store>): void
    "auth": {
      "register": {
        before(fn: BeforeHook<Store, RegisterDto>): void
        after(fn: AfterHook<Store, RegisterDto, UserDto>): void
      }
      "login": {
        before(fn: BeforeHook<Store, LoginDto>): void
        after(fn: AfterHook<Store, LoginDto, TokenDto>): void
      }
      "me": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, UserDto>): void
      }
      "whoami": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, UserDto>): void
      }
    }
    "posts": {
      "list": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, Array<PostDto>>): void
      }
      "create": {
        before(fn: BeforeHook<Store, CreatePostDto>): void
        after(fn: AfterHook<Store, CreatePostDto, PostDto>): void
      }
      "get": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, PostDto>): void
      }
      "remove": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, unknown>): void
      }
      "publish": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, PostDto>): void
      }
    }
    "comments": {
      "list": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, Array<CommentDto>>): void
      }
      "create": {
        before(fn: BeforeHook<Store, CreateCommentDto>): void
        after(fn: AfterHook<Store, CreateCommentDto, CommentDto>): void
      }
    }
    "users": {
      "uploadAvatar": {
        before(fn: BeforeHook<Store, {
          /** The image file. */
          "file": FileInput
        }>): void
        after(fn: AfterHook<Store, {
          /** The image file. */
          "file": FileInput
        }, UserDto>): void
      }
    }
    "test": {
      "reset": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, {
        "ok": boolean
      }>): void
      }
    }
}

/**
 * Тип регистратора хуков для ЭТОГО бэкенда. Объявите хуки в отдельном
 * файле и положите одной переменной в конфиг (`EberlyConfig.hooks`).
 * Передайте СВОЙ класс store параметром, чтобы `ctx` был типизирован:
 *
 *   import type { UserStore } from './userStore'
 *   export const hooks: Hooks<UserStore> = (h) => {
 *     h.posts.create.after(({ response, ctx }) => { … })
 *   }
 *
 * (Параметр НЕ выводится из `eberly.userStore` намеренно: это создало
 * бы цикл типов `eberly` ⇄ `Hooks`, т.к. `hooks` лежит внутри `eberly`.)
 */
export type Hooks<Store extends BaseStore = BaseStore> = (
  h: EberlyHookTree<Store>,
) => void

/**
 * База `World` — это сконфигурированный `eberly.worldStore` (или пустой
 * `BaseStore`, если не задан). Поэтому `world.<сценарий>()` и
 * `world.get/set` доступны и типизированы ровно как у пользователя,
 * только область — весь мир. Тип берётся из `eberly` тем же приёмом, что
 * и `Store` (никаких рантайм-условий — см. ARCHITECTURE.md §8).
 */
type ConfiguredWorldStore =
  typeof eberly extends { worldStore: new () => infer I extends BaseStore }
    ? I
    : BaseStore
const WorldStoreBase = ((eberly as { worldStore?: new () => BaseStore })
  .worldStore ?? BaseStore) as new () => ConfiguredWorldStore

export class World<
  Store extends BaseStore = InstanceType<typeof eberly.userStore>,
> extends WorldStoreBase {
  /**
   * Общий реестр хуков. Регистрация — статическая (один раз из конфига),
   * но `ctx` подставляется в момент запроса = store конкретного юзера.
   */
  private hookRegistry = new HookRegistry()

  constructor(
    public args: {
      /** URL бэкенда. Если не задан — берётся eberly.url из конфига. */
      url?: string
      /** Класс-хранилище. Если не задан — берётся eberly.userStore. */
      store?: new () => Store
    } = {},
  ) {
    super()
    const registrar = (eberly as { hooks?: (h: unknown) => void }).hooks
    if (registrar) registrar(this.buildHookTree())
    // world-store ходит АНОНИМНЫМ клиентом (без per-user заголовков);
    // ctx хуков для таких вызовов = сам world.
    ;(this as unknown as { api: unknown }).api = this.buildApiTree(
      this.makeRequest({ headers: {}, store: this }),
    )
  }

  /** Базовый URL с учётом server.url из схемы. */
  private baseUrl(): string {
    return (this.args.url ?? eberly.url).replace(/\/$/, '') + ""
  }

  private buildHookTree(): EberlyHookTree<Store> {
    const r = this.hookRegistry
    return {
      globalBefore: (fn: BeforeHook<Store>) => r.globalBefore({ fn }),
      globalAfter: (fn: AfterHook<Store>) => r.globalAfter({ fn }),
      globalRetry: (fn: RetryHook<Store>) => r.globalRetry({ fn }),
      "auth": {
        "register": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "auth.register", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "auth.register", fn }),
        },
        "login": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "auth.login", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "auth.login", fn }),
        },
        "me": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "auth.me", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "auth.me", fn }),
        },
        "whoami": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "auth.whoami", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "auth.whoami", fn }),
        },
      },
      "posts": {
        "list": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.list", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.list", fn }),
        },
        "create": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.create", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.create", fn }),
        },
        "get": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.get", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.get", fn }),
        },
        "remove": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.remove", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.remove", fn }),
        },
        "publish": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.publish", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.publish", fn }),
        },
      },
      "comments": {
        "list": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "comments.list", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "comments.list", fn }),
        },
        "create": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "comments.create", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "comments.create", fn }),
        },
      },
      "users": {
        "uploadAvatar": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "users.uploadAvatar", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "users.uploadAvatar", fn }),
        },
      },
      "test": {
        "reset": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "test.reset", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "test.reset", fn }),
        },
      },
    } as unknown as EberlyHookTree<Store>
  }

  /**
   * Создаёт `request`, замкнутый на заголовки и `store` (он же `ctx`
   * хуков). Один и тот же движок и для пользователя, и для world.
   */
  private makeRequest(cfg: {
    headers: Record<string, string>
    store: BaseStore
  }): RequestFn {
    const baseUrl = this.baseUrl()
    // Защита от прода: loopback можно всегда, остальное — из eberly.allowedHosts.
    assertHostAllowed({
      url: baseUrl,
      allowedHosts: (eberly as { allowedHosts?: string[] }).allowedHosts,
    })
    const registry = this.hookRegistry
    const { headers: baseHeaders, store } = cfg
    // Потолок ПОВТОРОВ (сверх первой попытки) для globalRetry-хуков —
    // защита от бесконечного цикла, если хук упрямо просит повтор.
    const maxRetries = (eberly as { maxRetries?: number }).maxRetries ?? 3

    return async (req): Promise<{ status: number; body: unknown }> => {
      const { method, path, opKey, input } = req

      // Retry-цикл: каждую попытку hookReq собирается ЗАНОВО и заново
      // прогоняются before-хуки, поэтому правки из retry-хука (напр.
      // свежий токен в ctx) подхватываются повторным before. `for (;;)`
      // крутится, пока не сработает return/throw в хвосте или `continue`.
      let attempt = 0
      for (;;) {
        const hookReq = {
          method,
          path,
          pathParams: { ...(input?.path ?? {}) },
          query: { ...(input?.query ?? {}) },
          body: input?.body,
          headers: { ...baseHeaders },
        }
        await registry.runBefore({ key: opKey, request: hookReq, ctx: store })

        let resolvedPath = path
        for (const [k, v] of Object.entries(hookReq.pathParams)) {
          resolvedPath = resolvedPath.replace(
            `{${k}}`,
            encodeURIComponent(String(v)),
          )
        }

        const url = new URL(baseUrl + resolvedPath)
        for (const [k, v] of Object.entries(hookReq.query)) {
          if (v !== undefined) url.searchParams.set(k, String(v))
        }

        const hasBody = hookReq.body !== undefined
        // Файловые (multipart) операции: FormData собирается ПОСЛЕ before-хуков
        // (тело к этому моменту — обычный объект, хуки видят/правят его как
        // JSON). Кодировка имён полей для массива файлов — из eberly.files
        // (дефолт 'repeat': веб-стандарт busboy/Go/Rust; oRPC ставит
        // 'bracket-index'). На retry FormData пересобирается заново.
        const fileFields = FILE_OPS[opKey]
        const form =
          fileFields && fileFields.length > 0 && hasBody
            ? await toMultipartFormData({
                body: hookReq.body as Record<string, unknown>,
                fileFields,
                encoding:
                  (eberly as { files?: { encoding?: FileEncoding } }).files?.encoding ?? 'repeat',
              })
            : undefined
        const isMultipart = form !== undefined

        const response = await fetch(url, {
          method,
          headers: {
            // multipart: content-type НЕ ставим — fetch сам выставит boundary.
            ...(isMultipart ? {} : hasBody ? { 'content-type': 'application/json' } : {}),
            ...hookReq.headers,
          },
          body: isMultipart ? form : hasBody ? JSON.stringify(hookReq.body) : undefined,
        })

        const text = await response.text()
        let data: unknown
        try {
          data = text ? JSON.parse(text) : undefined
        } catch {
          data = text
        }

        await registry.runAfter({
          key: opKey,
          request: hookReq,
          response: { status: response.status, body: data },
          ctx: store,
        })

        // Пока есть бюджет повторов — спрашиваем retry-хуки. Вернули
        // true → новый виток (заново before → fetch); иначе отдаём ответ.
        if (attempt < maxRetries) {
          const shouldRetry = await registry.runRetry({
            key: opKey,
            request: hookReq,
            response: { status: response.status, body: data },
            ctx: store,
          })
          if (shouldRetry) {
            attempt++
            continue
          }
        }

        return { status: response.status, body: data }
      }
    }
  }

  /** Дерево типизированных вызовов эндпоинтов поверх одного `request`. */
  private buildApiTree(request: RequestFn): WorldApi {
    return {
      "auth": {
        "register": async (input) =>
          new ApiResponse(await request({
            method: "POST",
            path: "/auth/register",
            opKey: "auth.register",
            input: input as RequestInput,
          })) as never,
        "login": async (input) =>
          new ApiResponse(await request({
            method: "POST",
            path: "/auth/login",
            opKey: "auth.login",
            input: input as RequestInput,
          })) as never,
        "me": async (input) =>
          new ApiResponse(await request({
            method: "GET",
            path: "/auth/me",
            opKey: "auth.me",
            input: input as RequestInput,
          })) as never,
        "whoami": async (input) =>
          new ApiResponse(await request({
            method: "GET",
            path: "/auth/whoami",
            opKey: "auth.whoami",
            input: input as RequestInput,
          })) as never,
      },
      "posts": {
        "list": async (input) =>
          new ApiResponse(await request({
            method: "GET",
            path: "/posts",
            opKey: "posts.list",
            input: input as RequestInput,
          })) as never,
        "create": async (input) =>
          new ApiResponse(await request({
            method: "POST",
            path: "/posts",
            opKey: "posts.create",
            input: input as RequestInput,
          })) as never,
        "get": async (input) =>
          new ApiResponse(await request({
            method: "GET",
            path: "/posts/{id}",
            opKey: "posts.get",
            input: input as RequestInput,
          })) as never,
        "remove": async (input) =>
          new ApiResponse(await request({
            method: "DELETE",
            path: "/posts/{id}",
            opKey: "posts.remove",
            input: input as RequestInput,
          })) as never,
        "publish": async (input) =>
          new ApiResponse(await request({
            method: "POST",
            path: "/posts/{id}/publish",
            opKey: "posts.publish",
            input: input as RequestInput,
          })) as never,
      },
      "comments": {
        "list": async (input) =>
          new ApiResponse(await request({
            method: "GET",
            path: "/posts/{id}/comments",
            opKey: "comments.list",
            input: input as RequestInput,
          })) as never,
        "create": async (input) =>
          new ApiResponse(await request({
            method: "POST",
            path: "/posts/{id}/comments",
            opKey: "comments.create",
            input: input as RequestInput,
          })) as never,
      },
      "users": {
        "uploadAvatar": async (input) =>
          new ApiResponse(await request({
            method: "POST",
            path: "/users/me/avatar",
            opKey: "users.uploadAvatar",
            input: input as RequestInput,
          })) as never,
      },
      "test": {
        "reset": async (input) =>
          new ApiResponse(await request({
            method: "POST",
            path: "/test/reset",
            opKey: "test.reset",
            input: input as RequestInput,
          })) as never,
      },
    }
  }

  /**
   * Создаёт «пользователя» — изолированный набор типизированных вызовов
   * эндпоинтов, который под капотом ходит fetch-запросами. `store.api`
   * указывает на то же дерево, поэтому методы-сценарии этого store
   * (`fullRegister` и т.п.) ходят от лица именно этого пользователя.
   */
  createUser(userArgs: CreateUserArgs = {}) {
    const StoreClass =
      this.args.store ?? (eberly.userStore as unknown as new () => Store)
    const store = new StoreClass()
    const tree = this.buildApiTree(
      this.makeRequest({ headers: { ...userArgs.headers }, store }),
    )
    ;(store as unknown as { api: unknown }).api = tree
    return Object.assign(store, tree)
  }
}
