// AUTO-GENERATED by eberly (generateClient) — НЕ редактировать вручную.
// Источник: Test Backend (oRPC) v1.0.0
// Режим клиента: test
// Перегенерация: pnpm run client:generate

import { BaseStore, ApiResponse, HookRegistry, assertHostAllowed, toMultipartFormData } from "eberly"
import type { BeforeHook, AfterHook, RetryHook } from "eberly"
import type { FileInput, FileEncoding, FileFieldMeta } from "eberly"
import { eberly } from "./eberly"

const FILE_OPS: Record<string, FileFieldMeta[]> = {}

type RequestInput = {
  path?: Record<string, string>
  query?: Record<string, string | number | boolean | undefined>
  body?: unknown
}

type RequestFn = (req: {
  method: string
  path: string
  opKey: string
  input?: RequestInput
}) => Promise<{ status: number; body: unknown }>

export type CreateUserArgs = {
  /** Заголовки, которые будут добавляться ко всем запросам этого пользователя. */
  headers?: Record<string, string>
}

export type WorldApi = {
    "posts": {
      /**
       * List all posts
       *
       * `GET /posts`
       */
      "list": (input?: {}) => Promise<ApiResponse<{ 200: Array<{
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        }> }>>
      /**
       * Create a post
       *
       * `POST /posts`
       */
      "create": (input: { body: {
          "title": string
          "content": string
        } }) => Promise<ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>>
      /**
       * Get a single post by id
       *
       * `GET /posts/{id}`
       */
      "get": (input: { path: { "id": string } }) => Promise<ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>>
      /**
       * Update a post
       *
       * `PATCH /posts/{id}`
       */
      "update": (input: { path: { "id": string }; body?: {
          "title"?: string
          "content"?: string
        } }) => Promise<ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>>
      /**
       * Delete a post
       *
       * `DELETE /posts/{id}`
       */
      "delete": (input: { path: { "id": string } }) => Promise<ApiResponse<{ 200: {
          "success": boolean
        } }>>
    }
    "auth": {
      /**
       * Register (stub: echoes input)
       *
       * `POST /auth/register`
       */
      "register": (input: { body: {
          "email": string
          "password": string
        } }) => Promise<ApiResponse<{ 200: {
          "email": string
          "password": string
        } }>>
      /**
       * Confirm registration code (stub: echoes input)
       *
       * `POST /auth/confirm`
       */
      "confirm": (input: { body: {
          "code": string
        } }) => Promise<ApiResponse<{ 200: {
          "code": string
        } }>>
      /**
       * Read current session (stub)
       *
       * `GET /auth/session`
       */
      "getGetSession": (input?: {}) => Promise<ApiResponse<{ 200: {
          "user": string
          "method": string
        } }>>
      /**
       * Refresh current session (stub)
       *
       * `POST /auth/session`
       */
      "postGetSession": (input: { body: {
          "token": string
        } }) => Promise<ApiResponse<{ 200: {
          "user": string
          "method": string
        } }>>
    }
    "admin": {
      /**
       * Wipe all in-memory data
       *
       * `POST /admin/clear-database`
       */
      "clearDatabase": (input?: {}) => Promise<ApiResponse<{ 200: {
          "success": boolean
        } }>>
    }
}

type EberlyHookTree<Store extends BaseStore> = {
    globalBefore(fn: BeforeHook<Store>): void
    globalAfter(fn: AfterHook<Store>): void
    globalRetry(fn: RetryHook<Store>): void
    "posts": {
      "list": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, Array<{
        "id": string
        "title": string
        "content": string
        "createdAt": string
        "updatedAt": string
      }>>): void
      }
      "create": {
        before(fn: BeforeHook<Store, {
          "title": string
          "content": string
        }>): void
        after(fn: AfterHook<Store, {
          "title": string
          "content": string
        }, {
        "id": string
        "title": string
        "content": string
        "createdAt": string
        "updatedAt": string
      }>): void
      }
      "get": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, {
        "id": string
        "title": string
        "content": string
        "createdAt": string
        "updatedAt": string
      }>): void
      }
      "update": {
        before(fn: BeforeHook<Store, {
          "title"?: string
          "content"?: string
        }>): void
        after(fn: AfterHook<Store, {
          "title"?: string
          "content"?: string
        }, {
        "id": string
        "title": string
        "content": string
        "createdAt": string
        "updatedAt": string
      }>): void
      }
      "delete": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, {
        "success": boolean
      }>): void
      }
    }
    "auth": {
      "register": {
        before(fn: BeforeHook<Store, {
          "email": string
          "password": string
        }>): void
        after(fn: AfterHook<Store, {
          "email": string
          "password": string
        }, {
        "email": string
        "password": string
      }>): void
      }
      "confirm": {
        before(fn: BeforeHook<Store, {
          "code": string
        }>): void
        after(fn: AfterHook<Store, {
          "code": string
        }, {
        "code": string
      }>): void
      }
      "getGetSession": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, {
        "user": string
        "method": string
      }>): void
      }
      "postGetSession": {
        before(fn: BeforeHook<Store, {
          "token": string
        }>): void
        after(fn: AfterHook<Store, {
          "token": string
        }, {
        "user": string
        "method": string
      }>): void
      }
    }
    "admin": {
      "clearDatabase": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, {
        "success": boolean
      }>): void
      }
    }
}

/**
 * Тип регистратора хуков для ЭТОГО бэкенда. Объявите хуки в отдельном
 * файле и положите одной переменной в конфиг (`EberlyConfig.hooks`).
 * Передайте СВОЙ класс store параметром, чтобы `ctx` был типизирован:
 *
 *   import type { UserStore } from './userStore'
 *   export const hooks: Hooks<UserStore> = (h) => {
 *     h.posts.create.after(({ response, ctx }) => { … })
 *   }
 *
 * (Параметр НЕ выводится из `eberly.userStore` намеренно: это создало
 * бы цикл типов `eberly` ⇄ `Hooks`, т.к. `hooks` лежит внутри `eberly`.)
 */
export type Hooks<Store extends BaseStore = BaseStore> = (
  h: EberlyHookTree<Store>,
) => void

/**
 * База `World` — это сконфигурированный `eberly.worldStore` (или пустой
 * `BaseStore`, если не задан). Поэтому `world.<сценарий>()` и
 * `world.get/set` доступны и типизированы ровно как у пользователя,
 * только область — весь мир. Тип берётся из `eberly` тем же приёмом, что
 * и `Store` (никаких рантайм-условий — см. ARCHITECTURE.md §8).
 */
type ConfiguredWorldStore =
  typeof eberly extends { worldStore: new () => infer I extends BaseStore }
    ? I
    : BaseStore
const WorldStoreBase = ((eberly as { worldStore?: new () => BaseStore })
  .worldStore ?? BaseStore) as new () => ConfiguredWorldStore

export class World<
  Store extends BaseStore = InstanceType<typeof eberly.userStore>,
> extends WorldStoreBase {
  /**
   * Общий реестр хуков. Регистрация — статическая (один раз из конфига),
   * но `ctx` подставляется в момент запроса = store конкретного юзера.
   */
  private hookRegistry = new HookRegistry()

  constructor(
    public args: {
      /** URL бэкенда. Если не задан — берётся eberly.url из конфига. */
      url?: string
      /** Класс-хранилище. Если не задан — берётся eberly.userStore. */
      store?: new () => Store
    } = {},
  ) {
    super()
    const registrar = (eberly as { hooks?: (h: unknown) => void }).hooks
    if (registrar) registrar(this.buildHookTree())
    // world-store ходит АНОНИМНЫМ клиентом (без per-user заголовков);
    // ctx хуков для таких вызовов = сам world.
    ;(this as unknown as { api: unknown }).api = this.buildApiTree(
      this.makeRequest({ headers: {}, store: this }),
    )
  }

  /** Базовый URL с учётом server.url из схемы. */
  private baseUrl(): string {
    return (this.args.url ?? eberly.url).replace(/\/$/, '') + "/api"
  }

  private buildHookTree(): EberlyHookTree<Store> {
    const r = this.hookRegistry
    return {
      globalBefore: (fn: BeforeHook<Store>) => r.globalBefore({ fn }),
      globalAfter: (fn: AfterHook<Store>) => r.globalAfter({ fn }),
      globalRetry: (fn: RetryHook<Store>) => r.globalRetry({ fn }),
      "posts": {
        "list": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.list", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.list", fn }),
        },
        "create": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.create", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.create", fn }),
        },
        "get": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.get", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.get", fn }),
        },
        "update": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.update", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.update", fn }),
        },
        "delete": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.delete", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.delete", fn }),
        },
      },
      "auth": {
        "register": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "auth.register", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "auth.register", fn }),
        },
        "confirm": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "auth.confirm", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "auth.confirm", fn }),
        },
        "getGetSession": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "auth.getGetSession", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "auth.getGetSession", fn }),
        },
        "postGetSession": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "auth.postGetSession", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "auth.postGetSession", fn }),
        },
      },
      "admin": {
        "clearDatabase": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "admin.clearDatabase", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "admin.clearDatabase", fn }),
        },
      },
    } as unknown as EberlyHookTree<Store>
  }

  /**
   * Создаёт `request`, замкнутый на заголовки и `store` (он же `ctx`
   * хуков). Один и тот же движок и для пользователя, и для world.
   */
  private makeRequest(cfg: {
    headers: Record<string, string>
    store: BaseStore
  }): RequestFn {
    const baseUrl = this.baseUrl()
    // Защита от прода: loopback можно всегда, остальное — из eberly.allowedHosts.
    assertHostAllowed({
      url: baseUrl,
      allowedHosts: (eberly as { allowedHosts?: string[] }).allowedHosts,
    })
    const registry = this.hookRegistry
    const { headers: baseHeaders, store } = cfg
    // Потолок ПОВТОРОВ (сверх первой попытки) для globalRetry-хуков —
    // защита от бесконечного цикла, если хук упрямо просит повтор.
    const maxRetries = (eberly as { maxRetries?: number }).maxRetries ?? 3

    return async (req): Promise<{ status: number; body: unknown }> => {
      const { method, path, opKey, input } = req

      // Retry-цикл: каждую попытку hookReq собирается ЗАНОВО и заново
      // прогоняются before-хуки, поэтому правки из retry-хука (напр.
      // свежий токен в ctx) подхватываются повторным before. `for (;;)`
      // крутится, пока не сработает return/throw в хвосте или `continue`.
      let attempt = 0
      for (;;) {
        const hookReq = {
          method,
          path,
          pathParams: { ...(input?.path ?? {}) },
          query: { ...(input?.query ?? {}) },
          body: input?.body,
          headers: { ...baseHeaders },
        }
        await registry.runBefore({ key: opKey, request: hookReq, ctx: store })

        let resolvedPath = path
        for (const [k, v] of Object.entries(hookReq.pathParams)) {
          resolvedPath = resolvedPath.replace(
            `{${k}}`,
            encodeURIComponent(String(v)),
          )
        }

        const url = new URL(baseUrl + resolvedPath)
        for (const [k, v] of Object.entries(hookReq.query)) {
          if (v !== undefined) url.searchParams.set(k, String(v))
        }

        const hasBody = hookReq.body !== undefined
        // Файловые (multipart) операции: FormData собирается ПОСЛЕ before-хуков
        // (тело к этому моменту — обычный объект, хуки видят/правят его как
        // JSON). Кодировка имён полей для массива файлов — из eberly.files
        // (дефолт 'repeat': веб-стандарт busboy/Go/Rust; oRPC ставит
        // 'bracket-index'). На retry FormData пересобирается заново.
        const fileFields = FILE_OPS[opKey]
        const form =
          fileFields && fileFields.length > 0 && hasBody
            ? await toMultipartFormData({
                body: hookReq.body as Record<string, unknown>,
                fileFields,
                encoding:
                  (eberly as { files?: { encoding?: FileEncoding } }).files?.encoding ?? 'repeat',
              })
            : undefined
        const isMultipart = form !== undefined

        const response = await fetch(url, {
          method,
          headers: {
            // multipart: content-type НЕ ставим — fetch сам выставит boundary.
            ...(isMultipart ? {} : hasBody ? { 'content-type': 'application/json' } : {}),
            ...hookReq.headers,
          },
          body: isMultipart ? form : hasBody ? JSON.stringify(hookReq.body) : undefined,
        })

        const text = await response.text()
        let data: unknown
        try {
          data = text ? JSON.parse(text) : undefined
        } catch {
          data = text
        }

        await registry.runAfter({
          key: opKey,
          request: hookReq,
          response: { status: response.status, body: data },
          ctx: store,
        })

        // Пока есть бюджет повторов — спрашиваем retry-хуки. Вернули
        // true → новый виток (заново before → fetch); иначе отдаём ответ.
        if (attempt < maxRetries) {
          const shouldRetry = await registry.runRetry({
            key: opKey,
            request: hookReq,
            response: { status: response.status, body: data },
            ctx: store,
          })
          if (shouldRetry) {
            attempt++
            continue
          }
        }

        return { status: response.status, body: data }
      }
    }
  }

  /** Дерево типизированных вызовов эндпоинтов поверх одного `request`. */
  private buildApiTree(request: RequestFn): WorldApi {
    return {
      "posts": {
        "list": async (input) =>
          new ApiResponse(await request({
            method: "GET",
            path: "/posts",
            opKey: "posts.list",
            input: input as RequestInput,
          })) as never,
        "create": async (input) =>
          new ApiResponse(await request({
            method: "POST",
            path: "/posts",
            opKey: "posts.create",
            input: input as RequestInput,
          })) as never,
        "get": async (input) =>
          new ApiResponse(await request({
            method: "GET",
            path: "/posts/{id}",
            opKey: "posts.get",
            input: input as RequestInput,
          })) as never,
        "update": async (input) =>
          new ApiResponse(await request({
            method: "PATCH",
            path: "/posts/{id}",
            opKey: "posts.update",
            input: input as RequestInput,
          })) as never,
        "delete": async (input) =>
          new ApiResponse(await request({
            method: "DELETE",
            path: "/posts/{id}",
            opKey: "posts.delete",
            input: input as RequestInput,
          })) as never,
      },
      "auth": {
        "register": async (input) =>
          new ApiResponse(await request({
            method: "POST",
            path: "/auth/register",
            opKey: "auth.register",
            input: input as RequestInput,
          })) as never,
        "confirm": async (input) =>
          new ApiResponse(await request({
            method: "POST",
            path: "/auth/confirm",
            opKey: "auth.confirm",
            input: input as RequestInput,
          })) as never,
        "getGetSession": async (input) =>
          new ApiResponse(await request({
            method: "GET",
            path: "/auth/session",
            opKey: "auth.getGetSession",
            input: input as RequestInput,
          })) as never,
        "postGetSession": async (input) =>
          new ApiResponse(await request({
            method: "POST",
            path: "/auth/session",
            opKey: "auth.postGetSession",
            input: input as RequestInput,
          })) as never,
      },
      "admin": {
        "clearDatabase": async (input) =>
          new ApiResponse(await request({
            method: "POST",
            path: "/admin/clear-database",
            opKey: "admin.clearDatabase",
            input: input as RequestInput,
          })) as never,
      },
    }
  }

  /**
   * Создаёт «пользователя» — изолированный набор типизированных вызовов
   * эндпоинтов, который под капотом ходит fetch-запросами. `store.api`
   * указывает на то же дерево, поэтому методы-сценарии этого store
   * (`fullRegister` и т.п.) ходят от лица именно этого пользователя.
   */
  createUser(userArgs: CreateUserArgs = {}) {
    const StoreClass =
      this.args.store ?? (eberly.userStore as unknown as new () => Store)
    const store = new StoreClass()
    const tree = this.buildApiTree(
      this.makeRequest({ headers: { ...userArgs.headers }, store }),
    )
    ;(store as unknown as { api: unknown }).api = tree
    return Object.assign(store, tree)
  }
}
