// AUTO-GENERATED by eberly (generateClient) — do not edit by hand.
// Source: Test Backend (oRPC) v1.0.0
// Client mode: test
// Regenerate: pnpm run client:generate

import { BaseStore, ApiResponse, HookRegistry, assertHostAllowed, toMultipartFormData } from "eberly"
import type { BeforeHook, AfterHook, RetryHook } from "eberly"
import type { FileInput, FileEncoding, FileFieldMeta } from "eberly"
import { eberly } from "./eberly"

const FILE_OPS: Record<string, FileFieldMeta[]> = {}

type RequestInput = {
  path?: Record<string, string | number | boolean>
  query?: Record<string, string | number | boolean | undefined>
  body?: unknown
}

type RequestFn = (req: {
  method: string
  path: string
  opKey: string
  input?: RequestInput
}) => Promise<{ status: number; body: unknown }>

export type CreateUserArgs = {
  /** Headers added to every request of this user. */
  headers?: Record<string, string>
}

export type WorldApi = {
    "posts": {
      /**
       * List all posts
       *
       * `GET /posts`
       */
      "list": (input?: {}) => Promise<ApiResponse<{ 200: Array<{
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        }> }>>
      /**
       * Create a post
       *
       * `POST /posts`
       */
      "create": (input: { body: {
          "title": string
          "content": string
        } }) => Promise<ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>>
      /**
       * Get a single post by id
       *
       * `GET /posts/{postId}`
       */
      "get": (input: { path: { "postId": string } }) => Promise<ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>>
      /**
       * Update a post
       *
       * `PATCH /posts/{postId}`
       */
      "update": (input: { path: { "postId": string }; body?: {
          "title"?: string
          "content"?: string
        } }) => Promise<ApiResponse<{ 200: {
          "id": string
          "title": string
          "content": string
          "createdAt": string
          "updatedAt": string
        } }>>
      /**
       * Delete a post
       *
       * `DELETE /posts/{postId}`
       */
      "delete": (input: { path: { "postId": string } }) => Promise<ApiResponse<{ 200: {
          "success": boolean
        } }>>
    }
    "auth": {
      /**
       * Register (stub: echoes input)
       *
       * `POST /auth/register`
       */
      "register": (input: { body: {
          "email": string
          "password": string
        } }) => Promise<ApiResponse<{ 200: {
          "email": string
          "password": string
        } }>>
      /**
       * Confirm registration code (stub: echoes input)
       *
       * `POST /auth/confirm`
       */
      "confirm": (input: { body: {
          "code": string
        } }) => Promise<ApiResponse<{ 200: {
          "code": string
        } }>>
      /**
       * Read current session (stub)
       *
       * `GET /auth/session`
       */
      "getGetSession": (input?: {}) => Promise<ApiResponse<{ 200: {
          "user": string
          "method": string
        } }>>
      /**
       * Refresh current session (stub)
       *
       * `POST /auth/session`
       */
      "postGetSession": (input: { body: {
          "token": string
        } }) => Promise<ApiResponse<{ 200: {
          "user": string
          "method": string
        } }>>
    }
    "admin": {
      /**
       * Wipe all in-memory data
       *
       * `POST /admin/clear-database`
       */
      "clearDatabase": (input?: {}) => Promise<ApiResponse<{ 200: {
          "success": boolean
        } }>>
    }
}

/**
 * The endpoint tree for TYPES only: `BodyOf<typeof api.posts.create>`
 * (also `QueryOf`, `PathOf`, `ResponseOf` from "eberly").
 * It does not call the backend, any access throws: use `world.createUser()`.
 */
export const api: WorldApi = new Proxy({} as WorldApi, {
  get(_, key) {
    if (typeof key === 'symbol') return undefined
    throw new Error(
      'api from the generated client is for types only (typeof api.<group>.<method>). ' +
        'To call the backend, use world.createUser().',
    )
  },
})

type EberlyHookTree<Store extends BaseStore> = {
    globalBefore(fn: BeforeHook<Store>): void
    globalAfter(fn: AfterHook<Store>): void
    globalRetry(fn: RetryHook<Store>): void
    "posts": {
      "list": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, Array<{
        "id": string
        "title": string
        "content": string
        "createdAt": string
        "updatedAt": string
      }>>): void
      }
      "create": {
        before(fn: BeforeHook<Store, {
          "title": string
          "content": string
        }>): void
        after(fn: AfterHook<Store, {
          "title": string
          "content": string
        }, {
        "id": string
        "title": string
        "content": string
        "createdAt": string
        "updatedAt": string
      }>): void
      }
      "get": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, {
        "id": string
        "title": string
        "content": string
        "createdAt": string
        "updatedAt": string
      }>): void
      }
      "update": {
        before(fn: BeforeHook<Store, {
          "title"?: string
          "content"?: string
        }>): void
        after(fn: AfterHook<Store, {
          "title"?: string
          "content"?: string
        }, {
        "id": string
        "title": string
        "content": string
        "createdAt": string
        "updatedAt": string
      }>): void
      }
      "delete": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, {
        "success": boolean
      }>): void
      }
    }
    "auth": {
      "register": {
        before(fn: BeforeHook<Store, {
          "email": string
          "password": string
        }>): void
        after(fn: AfterHook<Store, {
          "email": string
          "password": string
        }, {
        "email": string
        "password": string
      }>): void
      }
      "confirm": {
        before(fn: BeforeHook<Store, {
          "code": string
        }>): void
        after(fn: AfterHook<Store, {
          "code": string
        }, {
        "code": string
      }>): void
      }
      "getGetSession": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, {
        "user": string
        "method": string
      }>): void
      }
      "postGetSession": {
        before(fn: BeforeHook<Store, {
          "token": string
        }>): void
        after(fn: AfterHook<Store, {
          "token": string
        }, {
        "user": string
        "method": string
      }>): void
      }
    }
    "admin": {
      "clearDatabase": {
        before(fn: BeforeHook<Store, undefined>): void
        after(fn: AfterHook<Store, undefined, {
        "success": boolean
      }>): void
      }
    }
}

/**
 * Hook registrar type for THIS backend. Declare hooks in a separate file
 * and put them into the config as one variable (`EberlyConfig.hooks`).
 * Pass YOUR store class as the parameter so that `ctx` is typed:
 *
 *   import type { UserStore } from './userStore'
 *   export const hooks: Hooks<UserStore> = (h) => {
 *     h.posts.create.after(({ response, ctx }) => { … })
 *   }
 *
 * (The parameter is NOT inferred from `eberly.userStore` on purpose: that
 * would create a type cycle `eberly` ⇄ `Hooks`, since `hooks` lives in `eberly`.)
 */
export type Hooks<Store extends BaseStore = BaseStore> = (
  h: EberlyHookTree<Store>,
) => void

/**
 * The base of `World` is the configured `eberly.worldStore` (or a plain
 * `BaseStore` if none is set). So `world.<scenario>()` and
 * `world.get/set` are available and typed exactly as on a user, only
 * scoped to the whole world. The type comes from `eberly` the same way as
 * `Store` does (no runtime conditions).
 */
type ConfiguredWorldStore =
  typeof eberly extends { worldStore: new () => infer I extends BaseStore }
    ? I
    : BaseStore
const WorldStoreBase = ((eberly as { worldStore?: new () => BaseStore })
  .worldStore ?? BaseStore) as new () => ConfiguredWorldStore

export class World<
  Store extends BaseStore = InstanceType<typeof eberly.userStore>,
> extends WorldStoreBase {
  /**
   * Shared hook registry. Hooks are registered once (from the config), but
   * `ctx` is resolved per request: it is the store of that particular user.
   */
  private hookRegistry = new HookRegistry()

  constructor(
    public args: {
      /** Backend URL. Defaults to eberly.url from the config. */
      url?: string
      /** Store class. Defaults to eberly.userStore. */
      store?: new () => Store
    } = {},
  ) {
    super()
    const registrar = (eberly as { hooks?: (h: unknown) => void }).hooks
    if (registrar) registrar(this.buildHookTree())
    // The world store uses an ANONYMOUS client (no per-user headers);
    // hook ctx for these calls is the world itself.
    ;(this as unknown as { api: unknown }).api = this.buildApiTree(
      this.makeRequest({ headers: {}, store: this }),
    )
  }

  /** Base URL, including servers[0].url from the spec. */
  private baseUrl(): string {
    return (this.args.url ?? eberly.url).replace(/\/$/, '') + "/api"
  }

  private buildHookTree(): EberlyHookTree<Store> {
    const r = this.hookRegistry
    return {
      globalBefore: (fn: BeforeHook<Store>) => r.globalBefore({ fn }),
      globalAfter: (fn: AfterHook<Store>) => r.globalAfter({ fn }),
      globalRetry: (fn: RetryHook<Store>) => r.globalRetry({ fn }),
      "posts": {
        "list": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.list", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.list", fn }),
        },
        "create": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.create", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.create", fn }),
        },
        "get": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.get", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.get", fn }),
        },
        "update": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.update", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.update", fn }),
        },
        "delete": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "posts.delete", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "posts.delete", fn }),
        },
      },
      "auth": {
        "register": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "auth.register", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "auth.register", fn }),
        },
        "confirm": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "auth.confirm", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "auth.confirm", fn }),
        },
        "getGetSession": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "auth.getGetSession", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "auth.getGetSession", fn }),
        },
        "postGetSession": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "auth.postGetSession", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "auth.postGetSession", fn }),
        },
      },
      "admin": {
        "clearDatabase": {
          before: (fn: BeforeHook<Store>) => r.before({ key: "admin.clearDatabase", fn }),
          after: (fn: AfterHook<Store>) => r.after({ key: "admin.clearDatabase", fn }),
        },
      },
    } as unknown as EberlyHookTree<Store>
  }

  /**
   * Creates a `request` bound to the headers and the `store` (which is
   * also the hook `ctx`). The same engine serves users and the world.
   */
  private makeRequest(cfg: {
    headers: Record<string, string>
    store: BaseStore
  }): RequestFn {
    const baseUrl = this.baseUrl()
    // Production guard: loopback is always allowed, other hosts only from eberly.allowedHosts.
    assertHostAllowed({
      url: baseUrl,
      allowedHosts: (eberly as { allowedHosts?: string[] }).allowedHosts,
    })
    const registry = this.hookRegistry
    const { headers: baseHeaders, store } = cfg
    // Cap on RETRIES (on top of the first attempt) for globalRetry hooks,
    // so a hook that keeps asking for a retry cannot loop forever.
    const maxRetries = (eberly as { maxRetries?: number }).maxRetries ?? 3

    return async (req): Promise<{ status: number; body: unknown }> => {
      const { method, path, opKey, input } = req

      // Retry loop: every attempt rebuilds hookReq and runs the before hooks
      // AGAIN, so changes made by a retry hook (e.g. a fresh token in ctx)
      // are picked up by the next before. `for (;;)` spins until the
      // return/throw at the end or a `continue`.
      let attempt = 0
      for (;;) {
        const hookReq = {
          method,
          path,
          pathParams: { ...(input?.path ?? {}) },
          query: { ...(input?.query ?? {}) },
          body: input?.body,
          headers: { ...baseHeaders },
        }
        await registry.runBefore({ key: opKey, request: hookReq, ctx: store })

        let resolvedPath = path
        for (const [k, v] of Object.entries(hookReq.pathParams)) {
          resolvedPath = resolvedPath.replace(
            `{${k}}`,
            encodeURIComponent(String(v)),
          )
        }

        const url = new URL(baseUrl + resolvedPath)
        for (const [k, v] of Object.entries(hookReq.query)) {
          if (v !== undefined) url.searchParams.set(k, String(v))
        }

        const hasBody = hookReq.body !== undefined
        // File (multipart) operations: FormData is built AFTER the before hooks
        // (until then the body is a plain object that hooks see and edit as
        // JSON). Field naming for file arrays comes from eberly.files
        // (default 'repeat', the web standard for busboy/Go/Rust; oRPC uses
        // 'bracket-index'). On retry FormData is rebuilt from scratch.
        const fileFields = FILE_OPS[opKey]
        const form =
          fileFields && fileFields.length > 0 && hasBody
            ? await toMultipartFormData({
                body: hookReq.body as Record<string, unknown>,
                fileFields,
                encoding:
                  (eberly as { files?: { encoding?: FileEncoding } }).files?.encoding ?? 'repeat',
              })
            : undefined
        const isMultipart = form !== undefined

        const response = await fetch(url, {
          method,
          headers: {
            // multipart: no content-type here, fetch sets it with the boundary.
            ...(isMultipart ? {} : hasBody ? { 'content-type': 'application/json' } : {}),
            ...hookReq.headers,
          },
          body: isMultipart ? form : hasBody ? JSON.stringify(hookReq.body) : undefined,
        })

        const text = await response.text()
        let data: unknown
        try {
          data = text ? JSON.parse(text) : undefined
        } catch {
          data = text
        }

        await registry.runAfter({
          key: opKey,
          request: hookReq,
          response: { status: response.status, body: data },
          ctx: store,
        })

        // While retries are left, ask the retry hooks. true → another round
        // (before → fetch again); otherwise return the response.
        if (attempt < maxRetries) {
          const shouldRetry = await registry.runRetry({
            key: opKey,
            request: hookReq,
            response: { status: response.status, body: data },
            ctx: store,
          })
          if (shouldRetry) {
            attempt++
            continue
          }
        }

        return { status: response.status, body: data }
      }
    }
  }

  /** Tree of typed endpoint calls on top of a single `request`. */
  private buildApiTree(request: RequestFn): WorldApi {
    return {
      "posts": {
        "list": async (input) =>
          new ApiResponse({ ...(await request({
            method: "GET",
            path: "/posts",
            opKey: "posts.list",
            input: input as RequestInput,
          })), endpoint: "GET /posts" }) as never,
        "create": async (input) =>
          new ApiResponse({ ...(await request({
            method: "POST",
            path: "/posts",
            opKey: "posts.create",
            input: input as RequestInput,
          })), endpoint: "POST /posts" }) as never,
        "get": async (input) =>
          new ApiResponse({ ...(await request({
            method: "GET",
            path: "/posts/{postId}",
            opKey: "posts.get",
            input: input as RequestInput,
          })), endpoint: "GET /posts/{postId}" }) as never,
        "update": async (input) =>
          new ApiResponse({ ...(await request({
            method: "PATCH",
            path: "/posts/{postId}",
            opKey: "posts.update",
            input: input as RequestInput,
          })), endpoint: "PATCH /posts/{postId}" }) as never,
        "delete": async (input) =>
          new ApiResponse({ ...(await request({
            method: "DELETE",
            path: "/posts/{postId}",
            opKey: "posts.delete",
            input: input as RequestInput,
          })), endpoint: "DELETE /posts/{postId}" }) as never,
      },
      "auth": {
        "register": async (input) =>
          new ApiResponse({ ...(await request({
            method: "POST",
            path: "/auth/register",
            opKey: "auth.register",
            input: input as RequestInput,
          })), endpoint: "POST /auth/register" }) as never,
        "confirm": async (input) =>
          new ApiResponse({ ...(await request({
            method: "POST",
            path: "/auth/confirm",
            opKey: "auth.confirm",
            input: input as RequestInput,
          })), endpoint: "POST /auth/confirm" }) as never,
        "getGetSession": async (input) =>
          new ApiResponse({ ...(await request({
            method: "GET",
            path: "/auth/session",
            opKey: "auth.getGetSession",
            input: input as RequestInput,
          })), endpoint: "GET /auth/session" }) as never,
        "postGetSession": async (input) =>
          new ApiResponse({ ...(await request({
            method: "POST",
            path: "/auth/session",
            opKey: "auth.postGetSession",
            input: input as RequestInput,
          })), endpoint: "POST /auth/session" }) as never,
      },
      "admin": {
        "clearDatabase": async (input) =>
          new ApiResponse({ ...(await request({
            method: "POST",
            path: "/admin/clear-database",
            opKey: "admin.clearDatabase",
            input: input as RequestInput,
          })), endpoint: "POST /admin/clear-database" }) as never,
      },
    }
  }

  /**
   * Creates a "user": an isolated set of typed endpoint calls that uses
   * fetch under the hood. `store.api` points to the same tree, so the
   * scenario methods of this store (`fullRegister` etc.) act as this
   * very user.
   */
  createUser(userArgs: CreateUserArgs = {}) {
    const StoreClass =
      this.args.store ?? (eberly.userStore as unknown as new () => Store)
    const store = new StoreClass()
    const tree = this.buildApiTree(
      this.makeRequest({ headers: { ...userArgs.headers }, store }),
    )
    ;(store as unknown as { api: unknown }).api = tree
    return Object.assign(store, tree)
  }
}
