// Слой «модель операций → папка `api/` для агента».
//
// Рядом со сгенерированным клиентом лежит `api/INDEX.md` (одна строка на
// эндпоинт) и по файлу `<группа>.<метод>.md` на эндпоинт: описание,
// готовый вызов, вход, ответы и определения всех нужных именованных типов.
// Агент читает INDEX → 2–3 нужных файла, а не весь generated.ts.
//
// Всё строится кодом из свагера, детерминированно. Первая строка каждого
// файла — `DOCS_MARKER`: по ней generate-client.ts удаляет устаревшие
// файлы, не трогая чужие (папка `api/` может оказаться кодом пользователя).
// Формат `.md`, а не `.ts`: `.ts` попал бы в `include` tsconfig, и IDE
// предлагала бы автоимпорт `PostDto` из двух мест.

import type { ClientMode } from '../config'
import type { SchemaNames } from './names'
import type { Operation, Param } from './operations'
import { buildInputType } from './render'
import { isFileSchema, resolveRef, SCHEMA_REF_PREFIX, schemaToType } from './schema'
import type { Json } from './types'

export const DOCS_MARKER =
  '<!-- AUTO-GENERATED by eberly. Do not edit. Regenerate: pnpm run client:generate -->'

/** Глубина вложенных объектов в примере вызова; глубже — `{}`. */
const EXAMPLE_MAX_DEPTH = 3

/** Длиннее — пример тела переносится построчно. */
const INLINE_LITERAL_MAX = 80

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/

/** Рендерит `INDEX.md` и по файлу на эндпоинт. */
export function renderEndpointDocs(args: {
  spec: Json
  operations: Operation[]
  names: SchemaNames
  mode: ClientMode
}): { fileName: string; content: string }[] {
  const { spec, operations, names, mode } = args
  const files = operations.map((op) => ({
    fileName: `${docBaseName(op)}.md`,
    content: renderEndpointDoc({ spec, op, names, mode }),
  }))
  return [{ fileName: 'INDEX.md', content: renderIndex({ operations }) }, ...files]
}

/** `posts.create`; символы, недопустимые в имени файла, → `_`. */
function docBaseName(op: Operation): string {
  return `${op.group}.${op.name}`.replace(/[^A-Za-z0-9_.-]/g, '_')
}

/** Первая непустая строка — для однострочных мест (INDEX). */
function firstLine(text: string | undefined): string | undefined {
  return text
    ?.split(/\r?\n/)
    .map((l) => l.trim())
    .find((l) => l !== '')
}

const route = (op: Operation): string => `${op.method.toUpperCase()} ${op.path}`

function renderIndex(args: { operations: Operation[] }): string {
  const { operations } = args
  const groups = new Map<string, Operation[]>()
  for (const op of operations) groups.set(op.group, [...(groups.get(op.group) ?? []), op])

  const lines = [
    DOCS_MARKER,
    '# API index',
    'Open `<group>.<method>.md` for details. Call as `user.<group>.<method>(…)`.',
  ]
  for (const [group, ops] of groups) {
    lines.push('', `## ${group}`)
    for (const op of ops) {
      const summary = firstLine(op.summary)
      const deprecated = op.deprecated && !/deprecated/i.test(summary ?? '') ? ' (deprecated)' : ''
      const text = summary ? ` — ${summary}${deprecated}` : deprecated ? ` —${deprecated}` : ''
      lines.push(`- ${docBaseName(op)} — ${route(op)}${text}`)
    }
  }
  return `${lines.join('\n')}\n`
}

function renderEndpointDoc(args: { spec: Json; op: Operation; names: SchemaNames; mode: ClientMode }): string {
  const { spec, op, names, mode } = args
  const type = (schema: Json | undefined): string => schemaToType({ schema, spec, names })

  const out = [DOCS_MARKER, `# ${op.group}.${op.name} — ${route(op)}`, '']
  if (op.deprecated) out.push('**Deprecated.**', '')
  for (const text of [op.summary, op.description]) {
    if (text?.trim()) out.push(text.trim(), '')
  }

  out.push('## Call', '```ts', ...renderCall({ spec, op, mode }), '```', '')

  const input = buildInputType({ op, bodyType: op.bodySchema ? type(op.bodySchema) : null, indent: 0 })
  if (input.type !== '{}') out.push('## Input', '```ts', input.type, '```', '')

  // Описание ответа — комментарием: в конце строки, а у многострочного
  // типа — строкой выше, чтобы не висело после закрывающей скобки.
  const responses = op.responses.map((r) => {
    const comment = firstLine(r.description)
    const line = `${r.status}: ${type(r.schema)}`
    if (!comment) return line
    return line.includes('\n') ? `// ${comment}\n${line}` : `${line} // ${comment}`
  })
  out.push('## Responses', '```ts', ...responses, '```')

  const decls = collectNamedTypes({
    spec,
    names,
    roots: [op.bodySchema, ...op.responses.map((r) => r.schema)],
  }).map(({ key, name }) => `type ${name} = ${type(spec.components.schemas[key])}`)
  if (decls.length > 0) out.push('', '## Types', '```ts', ...decls, '```')

  return `${out.join('\n')}\n`
}

/**
 * Пример значения path/query-параметра под его тип: сложное значение →
 * JSON-строка, параметр типа `string` → строка (`example: 5` у
 * строкового параметра не должен ломать пример).
 */
function exampleParamValue(args: { param: Param; spec: Json }): unknown {
  const { param, spec } = args
  const value = renderExampleValue({ schema: param.schema ?? { type: 'string' }, spec })
  if (!['string', 'number', 'boolean'].includes(typeof value)) return JSON.stringify(value)
  return param.type === 'string' ? String(value) : value
}

/** Строки блока Call: вызов с обязательными полями + `assert` (режим `test`). */
function renderCall(args: { spec: Json; op: Operation; mode: ClientMode }): string[] {
  const { spec, op, mode } = args
  const input: Record<string, unknown> = {}

  if (op.pathParams.length > 0) {
    input.path = Object.fromEntries(op.pathParams.map((param) => [param.name, exampleParamValue({ param, spec })]))
  }
  const query = op.queryParams.filter((p) => p.required)
  if (query.length > 0) {
    input.query = Object.fromEntries(query.map((param) => [param.name, exampleParamValue({ param, spec })]))
  }
  if (op.bodySchema) input.body = renderExampleValue({ schema: op.bodySchema, spec })

  const accessor = (key: string): string => (IDENTIFIER.test(key) ? `.${key}` : `[${JSON.stringify(key)}]`)
  const fn = `user${accessor(op.group)}${accessor(op.name)}`
  const arg = Object.keys(input).length > 0 ? toLiteral({ value: input, indent: 0 }) : ''

  if (mode === 'frontend') return [`const data = await ${fn}(${arg})`]
  const success = op.responses.find((r) => r.status >= 200 && r.status < 300)
  return [`const res = await ${fn}(${arg})`, ...(success ? [`res.assert(${success.status})`] : [])]
}

/**
 * Пример значения по схеме: `example` → первое из `examples` → первое
 * `enum` / `const` → заглушка по типу (`"string"`, `0`, `true`, `[]`, для
 * файла `"./path/to/file"`). У объектов — только обязательные поля,
 * рекурсивно, до глубины 3; `$ref`, уже открытый выше по пути, → `{}`.
 */
export function renderExampleValue(args: {
  schema: Json | undefined
  spec: Json
  depth?: number
  visited?: ReadonlySet<string>
}): unknown {
  const { schema, spec, depth = 0, visited = new Set<string>() } = args
  if (!schema) return {}

  const own = pickExample(schema)
  if (own.found) return own.value

  if (typeof schema.$ref === 'string') {
    const ref: string = schema.$ref
    if (visited.has(ref)) return {}
    return renderExampleValue({
      schema: resolveRef({ ref, spec }),
      spec,
      depth,
      visited: new Set([...visited, ref]),
    })
  }

  const next = (sub: { schema: Json | undefined; depth?: number }): unknown =>
    renderExampleValue({ spec, depth, visited, ...sub })

  if (isFileSchema(schema)) return './path/to/file'
  if (Array.isArray(schema.oneOf) || Array.isArray(schema.anyOf)) {
    return next({ schema: (schema.oneOf ?? schema.anyOf)[0] })
  }
  if (Array.isArray(schema.allOf)) {
    const parts = schema.allOf.map((s: Json) => next({ schema: s }))
    const objects = parts.filter((p: unknown) => typeof p === 'object' && p !== null && !Array.isArray(p))
    return objects.length === parts.length ? Object.assign({}, ...objects) : parts[0]
  }

  const types: unknown[] = Array.isArray(schema.type) ? schema.type : [schema.type]
  const type = types.find((t) => t !== 'null') ?? (schema.properties ? 'object' : types[0])
  switch (type) {
    case 'string':
      return 'string'
    case 'number':
    case 'integer':
      return 0
    case 'boolean':
      return true
    case 'null':
      return null
    case 'array':
      return []
    case 'object': {
      if (depth >= EXAMPLE_MAX_DEPTH) return {}
      const props: Json = schema.properties ?? {}
      const required: string[] = schema.required ?? []
      return Object.fromEntries(
        Object.keys(props)
          .filter((k) => required.includes(k))
          .map((k) => [k, next({ schema: props[k], depth: depth + 1 })]),
      )
    }
    default:
      return {}
  }
}

/** Значение из `example` / `examples[0]` / `enum[0]` / `const` самой схемы. */
function pickExample(schema: Json): { found: boolean; value?: unknown } {
  if (schema.example !== undefined) return { found: true, value: schema.example }
  if (Array.isArray(schema.examples) && schema.examples.length > 0) return { found: true, value: schema.examples[0] }
  if (Array.isArray(schema.enum) && schema.enum.length > 0) return { found: true, value: schema.enum[0] }
  if (schema.const !== undefined) return { found: true, value: schema.const }
  return { found: false }
}

const literalKey = (k: string): string => (IDENTIFIER.test(k) ? k : JSON.stringify(k))

/** JS-литерал значения в одну строку; ключи без кавычек, где можно. */
function inlineLiteral(value: unknown): string {
  if (Array.isArray(value)) return value.length === 0 ? '[]' : `[${value.map(inlineLiteral).join(', ')}]`
  if (typeof value === 'object' && value !== null) {
    const entries = Object.entries(value)
    if (entries.length === 0) return '{}'
    return `{ ${entries.map(([k, v]) => `${literalKey(k)}: ${inlineLiteral(v)}`).join(', ')} }`
  }
  return value === undefined ? 'undefined' : JSON.stringify(value)
}

/**
 * JS-литерал значения: в одну строку, если влезает в `INLINE_LITERAL_MAX`,
 * иначе построчно с отступом 2 (`indent` — уровень закрывающей скобки).
 */
function toLiteral(args: { value: unknown; indent: number }): string {
  const { value, indent } = args
  const inline = inlineLiteral(value)
  if (typeof value !== 'object' || value === null || inline.length + indent * 2 <= INLINE_LITERAL_MAX) {
    return inline
  }
  const pad = '  '.repeat(indent + 1)
  const nested = (v: unknown): string => toLiteral({ value: v, indent: indent + 1 })
  const [open, close, lines] = Array.isArray(value)
    ? ['[', ']', value.map((v) => `${pad}${nested(v)},`)]
    : ['{', '}', Object.entries(value).map(([k, v]) => `${pad}${literalKey(k)}: ${nested(v)},`)]
  return `${open}\n${lines.join('\n')}\n${'  '.repeat(indent)}${close}`
}

/**
 * Именованные типы (`components/schemas`), на которые транзитивно
 * ссылаются `roots`. Каждый ровно один раз, в порядке обнаружения; обход
 * защищён от рекурсии множеством посещённых ссылок.
 */
export function collectNamedTypes(args: {
  spec: Json
  names: SchemaNames
  roots: Array<Json | undefined>
}): { key: string; name: string }[] {
  const { spec, names, roots } = args
  const found: { key: string; name: string }[] = []
  const seen = new Set<string>()

  const walk = (node: unknown): void => {
    if (Array.isArray(node)) return node.forEach(walk)
    if (typeof node !== 'object' || node === null) return
    const ref: unknown = (node as Json).$ref
    if (typeof ref === 'string') {
      if (seen.has(ref)) return
      seen.add(ref)
      const key = ref.startsWith(SCHEMA_REF_PREFIX) ? ref.slice(SCHEMA_REF_PREFIX.length) : undefined
      const name = key === undefined ? undefined : names.get(key)
      if (key !== undefined && name) found.push({ key, name })
      walk(resolveRef({ ref, spec }))
    }
    for (const [k, v] of Object.entries(node)) {
      // `example` — данные, а не схема: `$ref` внутри него не ссылка.
      if (k !== 'example' && k !== 'examples') walk(v)
    }
  }
  roots.forEach(walk)
  return found
}
