// Слой «модель операций → исходный текст клиента».
//
// Здесь рождается содержимое будущего сгенерированного файла (world):
// класс `World` с методом `createUser()`, сгруппированными по
// operationId типизированными вызовами и общей функцией `request`.
// Это единственное место, где задаётся форма публичного API клиента.

import type { Operation } from './operations'
import type { Json } from './types'

/** Описывает тип единственного аргумента-объекта метода (паттерн options object). */
function buildInputType(op: Operation): { type: string; optional: boolean } {
  const parts: string[] = []

  if (op.pathParams.length > 0) {
    const fields = op.pathParams.map((p) => `${JSON.stringify(p)}: string`).join('; ')
    parts.push(`path: { ${fields} }`)
  }
  if (op.queryParams.length > 0) {
    const fields = op.queryParams.map((p) => `${JSON.stringify(p)}?: string | number | boolean`).join('; ')
    parts.push(`query?: { ${fields} }`)
  }
  if (op.bodyType) {
    parts.push(`body${op.bodyRequired ? '' : '?'}: ${op.bodyType}`)
  }

  if (parts.length === 0) return { type: '{}', optional: true }

  const optional = op.pathParams.length === 0 && (!op.bodyType || !op.bodyRequired)
  return { type: `{ ${parts.join('; ')} }`, optional }
}

/** Рендерит финальный исходник клиента (world). */
export function renderClient(args: {
  spec: Json
  operations: Operation[]
  internalStoreImport: string
  configImport: string
}): string {
  const { spec, operations, internalStoreImport, configImport } = args
  const basePath: string = spec.servers?.[0]?.url ?? ''

  const groups = new Map<string, Operation[]>()
  for (const op of operations) {
    const list = groups.get(op.group) ?? []
    list.push(op)
    groups.set(op.group, list)
  }

  const groupBlocks = [...groups.entries()].map(([group, ops]) => {
    const methods = ops.map((op) => {
      const { type, optional } = buildInputType(op)
      const inputParam = `input${optional ? '?' : ''}: ${type}`
      const doc = op.summary ? `\n        /** ${op.summary} */` : ''
      return `${doc}
        ${JSON.stringify(op.name)}: (${inputParam}): Promise<${op.responseType}> =>
          request({
            method: ${JSON.stringify(op.method.toUpperCase())},
            path: ${JSON.stringify(op.path)},
            input: input as RequestInput,
          }) as Promise<${op.responseType}>,`
    })
    return `      ${JSON.stringify(group)}: {\n${methods.join('\n')}\n      },`
  })

  return `// AUTO-GENERATED by ebely (generateClient) — НЕ редактировать вручную.
// Источник: ${spec.info?.title ?? 'OpenAPI spec'} v${spec.info?.version ?? '?'}
// Перегенерация: pnpm run client:generate

import { InternalStore } from ${JSON.stringify(internalStoreImport)}
import { ebely } from ${JSON.stringify(configImport)}

type RequestInput = {
  path?: Record<string, string>
  query?: Record<string, string | number | boolean | undefined>
  body?: unknown
}

export type CreateUserArgs = {
  /** Заголовки, которые будут добавляться ко всем запросам этого пользователя. */
  headers?: Record<string, string>
}

export class World<
  Store extends InternalStore = InstanceType<typeof ebely.internalStore>,
> {
  constructor(
    public args: {
      /** URL бэкенда. Если не задан — берётся ebely.url из конфига. */
      url?: string
      /** Класс-хранилище. Если не задан — берётся ebely.internalStore. */
      store?: new () => Store
    } = {},
  ) {}

  /** Базовый URL с учётом server.url из схемы. */
  private baseUrl(): string {
    return (this.args.url ?? ebely.url).replace(/\\/$/, '') + ${JSON.stringify(basePath)}
  }

  /**
   * Создаёт «пользователя» — изолированный набор типизированных вызовов
   * эндпоинтов, который под капотом ходит fetch-запросами.
   */
  createUser(userArgs: CreateUserArgs = {}) {
    const baseUrl = this.baseUrl()
    const StoreClass =
      this.args.store ?? (ebely.internalStore as unknown as new () => Store)
    const store = new StoreClass()

    const request = async (req: {
      method: string
      path: string
      input?: RequestInput
    }): Promise<unknown> => {
      const { method, path, input } = req

      let resolvedPath = path
      for (const [key, value] of Object.entries(input?.path ?? {})) {
        resolvedPath = resolvedPath.replace(
          \`{\${key}}\`,
          encodeURIComponent(String(value)),
        )
      }

      const url = new URL(baseUrl + resolvedPath)
      for (const [key, value] of Object.entries(input?.query ?? {})) {
        if (value !== undefined) url.searchParams.set(key, String(value))
      }

      const hasBody = input?.body !== undefined
      const response = await fetch(url, {
        method,
        headers: {
          ...(hasBody ? { 'content-type': 'application/json' } : {}),
          ...userArgs.headers,
        },
        body: hasBody ? JSON.stringify(input!.body) : undefined,
      })

      const text = await response.text()
      const data = text ? JSON.parse(text) : undefined

      if (!response.ok) {
        throw new Error(
          \`Request \${method} \${resolvedPath} failed with \${response.status}: \${text}\`,
        )
      }

      return data
    }

    return Object.assign(store, {
${groupBlocks.join('\n')}
    })
  }
}
`
}
