// AUTO-GENERATED by evely (generateClient) — НЕ редактировать вручную.
// Источник: Test Backend (oRPC) v1.0.0
// Перегенерация: pnpm run client:generate

import { InternalStore } from "ebely"
import { evely } from "./evely"

type RequestInput = {
  path?: Record<string, string>
  query?: Record<string, string | number | boolean | undefined>
  body?: unknown
}

export type CreateUserArgs = {
  /** Заголовки, которые будут добавляться ко всем запросам этого пользователя. */
  headers?: Record<string, string>
}

export class World<
  Store extends InternalStore = InstanceType<typeof evely.internalStore>,
> {
  constructor(
    public args: {
      /** URL бэкенда. Если не задан — берётся evely.url из конфига. */
      url?: string
      /** Класс-хранилище. Если не задан — берётся evely.internalStore. */
      store?: new () => Store
    } = {},
  ) {}

  /** Базовый URL с учётом server.url из схемы. */
  private baseUrl(): string {
    return (this.args.url ?? evely.url).replace(/\/$/, '') + "/api"
  }

  /**
   * Создаёт «пользователя» — изолированный набор типизированных вызовов
   * эндпоинтов, который под капотом ходит fetch-запросами.
   */
  createUser(userArgs: CreateUserArgs = {}) {
    const baseUrl = this.baseUrl()
    const StoreClass =
      this.args.store ?? (evely.internalStore as unknown as new () => Store)
    const store = new StoreClass()

    const request = async (req: {
      method: string
      path: string
      input?: RequestInput
    }): Promise<unknown> => {
      const { method, path, input } = req

      let resolvedPath = path
      for (const [key, value] of Object.entries(input?.path ?? {})) {
        resolvedPath = resolvedPath.replace(
          `{${key}}`,
          encodeURIComponent(String(value)),
        )
      }

      const url = new URL(baseUrl + resolvedPath)
      for (const [key, value] of Object.entries(input?.query ?? {})) {
        if (value !== undefined) url.searchParams.set(key, String(value))
      }

      const hasBody = input?.body !== undefined
      const response = await fetch(url, {
        method,
        headers: {
          ...(hasBody ? { 'content-type': 'application/json' } : {}),
          ...userArgs.headers,
        },
        body: hasBody ? JSON.stringify(input!.body) : undefined,
      })

      const text = await response.text()
      const data = text ? JSON.parse(text) : undefined

      if (!response.ok) {
        throw new Error(
          `Request ${method} ${resolvedPath} failed with ${response.status}: ${text}`,
        )
      }

      return data
    }

    return Object.assign(store, {
      "posts": {

        /** List all posts */
        "list": (input?: {}): Promise<Array<{
        "id": string
        "title": string
        "content": string
        "createdAt": string
        "updatedAt": string
      }>> =>
          request({
            method: "GET",
            path: "/posts",
            input: input as RequestInput,
          }) as Promise<Array<{
        "id": string
        "title": string
        "content": string
        "createdAt": string
        "updatedAt": string
      }>>,

        /** Create a post */
        "create": (input: { body: {
          "title": string
          "content": string
        } }): Promise<{
        "id": string
        "title": string
        "content": string
        "createdAt": string
        "updatedAt": string
      }> =>
          request({
            method: "POST",
            path: "/posts",
            input: input as RequestInput,
          }) as Promise<{
        "id": string
        "title": string
        "content": string
        "createdAt": string
        "updatedAt": string
      }>,

        /** Get a single post by id */
        "get": (input: { path: { "id": string } }): Promise<{
        "id": string
        "title": string
        "content": string
        "createdAt": string
        "updatedAt": string
      }> =>
          request({
            method: "GET",
            path: "/posts/{id}",
            input: input as RequestInput,
          }) as Promise<{
        "id": string
        "title": string
        "content": string
        "createdAt": string
        "updatedAt": string
      }>,

        /** Update a post */
        "update": (input: { path: { "id": string }; body?: {
          "title"?: string
          "content"?: string
        } }): Promise<{
        "id": string
        "title": string
        "content": string
        "createdAt": string
        "updatedAt": string
      }> =>
          request({
            method: "PATCH",
            path: "/posts/{id}",
            input: input as RequestInput,
          }) as Promise<{
        "id": string
        "title": string
        "content": string
        "createdAt": string
        "updatedAt": string
      }>,

        /** Delete a post */
        "delete": (input: { path: { "id": string } }): Promise<{
        "success": boolean
      }> =>
          request({
            method: "DELETE",
            path: "/posts/{id}",
            input: input as RequestInput,
          }) as Promise<{
        "success": boolean
      }>,
      },
    })
  }
}
